### ISSUE TITLE
Problem with inclusion in a bootstrap grid

### ISSUE THREAD

**Issue by NRJMons** [yn1323/TimeTable.js#1]
Hi yn1323

First of all, thx for this project, it helped me a lot in my investigations.

I'm facing now a small problem with the timetable canvas.
If I enclose the table in a regular div, no issue and the refresh works great.
If I enclose the table in a bootstrap gris, using <div class="col-md-9", which I need to do to show a side panel to edit entries in details, the canvas position is skewed. It appears not correctly and shifts to the bottom and right.

I tried changing the position of the canvas element to a different "position" parameter and not use absolute, but nothing works.

Can you please help me?

Thx a lot in advance

regards

Nico

**Comment by yn1323** [comment]
Hi NRJMons,

Thank you for using TimeTable.js and reporting the issue.

I added the option of "useBootstrap". 
Please follow the readme.mod. 

If the issue still occurs, please let me know the detail.


Thanks,
yn1323

**Comment by NRJMons** [comment]
Perfect man, that works smoothly

Thanks a lot for your swift reaction and resolution.
Very much appreciated.

BTW, I added the possibility to include text in the input object and use that comment as a text inside the drawn line, which I expanded a bit (double the height) to manage the text.

works like a charm

<img width="1653" alt="timetable" src="https://user-images.githubusercontent.com/4720355/48366875-600e1100-e6af-11e8-838f-ac0bf51e04b6.png">

**Comment by yn1323** [comment]
Im glad to hear the modificaiton went alright!
And thanks for sharing the way of how TimeTable.js used.
Very nice idea to show text inside the line!

Will conside to add that in future function!

**Comment by NRJMons** [comment]
Hi yn1323

In fact, I modified the shiftObj structure like so:

“1”: “10:00-12:00” is replaced by “1”:Array

In the array, I push all the data I need like that:

[“10:00-12:00”, “Comments blablabla”, id_in_DB_of_the_item_displayed]

I modified the initialisation so that the array is taken as a whole and I fetch only item 0 of the array as the time required by default

I modified also the drawLine method liked so:

var strokeHeight = 20; // Original = 10
        shape.graphics
            .setStrokeStyle(strokeHeight)
            .beginStroke(barColor)
            .moveTo(sc.x,sc.y)
            .lineTo(ec.x,ec.y)
            .endStroke();
        
        // Add shape
        this.stage.addChild(shape);
        // Draw comments
        
        var textShape = new createjs.Text(text, " 12px Titillium Web", "#ffffff");
        textShape.set({
            textAlign: 'center',
            x: sc.x+(ec.x-sc.x)/2,
            y:sc.y-10
        });
        
        this.stage.addChild(textShape);
        this.stageUpdate();
        return shape;


That’s all ;)


NRJMons

**Comment by NRJMons** [comment]
Sorry I forgot something

I also modified the drawLine signature like this:

drawLine(index,sTime,eTime,color,over,text) {


To pass the text coming from shiftObj:

initialDraw(){
        let timeData = super.getIndexAndTime(this.v.shiftTime);
        let gen = this.u.colorTimeGenerator(timeData);
        for(;;){
            // Analyze object
            // MODIFIED: get comment and id too
            let [index,color,s,e, comment, id] = gen.next().value;
            // End of generator
            if(!index)break;
            let [sTime,eTime,over] = this.setDrawParameter(index,s,e);
            // Draw Line
            let shape = this.drawLine(index,sTime,eTime,color,over, comment);
            // Add mouse over Tooltip event
            let time = `${super.int2Time(s)}-${super.int2Time(e)}`;
            let startCoordinate = this.u.getCoordinateFromCustomAttribute(index,s);
            this.addTooltipEvent(shape, index, time, startCoordinate, id);
        }
        // DISABLE BAR CREATION
        //this.addCreateBarEvent();
    }

And of course also colorTimeGenerator:

colorTimeGenerator(obj){
        let indexArray = Object.keys(obj);
        while(true){
            // Loop for index
            for(let i = 0; i < indexArray.length; i++){
                let colorTimeArray = obj[indexArray[i]];
                // Loop for time in 1 person
                for(let j = 0; j < colorTimeArray.length; j++){
                    let colorTime = colorTimeArray[j];
                    // MODIFIED: get comment and id too
                    yield [
                        indexArray[i],
                        colorTime["color"],
                        colorTime["startTime"],
                        colorTime["endTime"],
                        colorTime["comments"],
                        colorTime["id"]
                    ];
                }
            }
            yield [false,false,false,false];
        }
    }

And also getIndexAndTime:

getIndexAndTime(shift){
        let obj = {};
        // Access to Object rooted to Index Key
        for(let key in shift){
            let indexObj = shift[key];
            // Access to Object rooted to Name Key
            for(let name in indexObj){
                let colorObj = indexObj[name];
                // tempArray to store data of 1 person
                let tempArray = [];
                // Access to Object rooted to Color Key
                for(let i in colorObj){
                    let obj = colorObj[i];
                    // To fetch as String, made another loop
                    for(let color in obj){
                        let tempObj = {};
                        // MODIFIED: get time in array index 0
                        let [start,end] = this.twoTime2Int(obj[color][0]);
                        tempObj["color"] = color;
                        tempObj["startTime"] = start;
                        tempObj["endTime"] = end;
                        // MODIFIED: get comment and id in index 1 and 2
                        tempObj["comments"] = obj[color][1];
                        tempObj["id"] = obj[color][2];
                        tempArray.push(tempObj);
                    }
                }
                obj[`${key}`] = tempArray;
            }
        }
        return obj;
    }
